# Generated by Django 4.1.1 on 2022-09-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('lead_at', models.DateField(verbose_name='Время выполнения')),
            ],
        ),
    ]
