# Generated by Django 4.1.1 on 2022-09-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='detail_description',
            field=models.TextField(default='', verbose_name='Детальное описание'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('In Progress', 'В работе'), ('Completed', 'Завершена')], max_length=50, verbose_name='Статус'),
        ),
    ]
